### ISSUE TITLE
Версия OpenCart 3.0.3.1

### ISSUE THREAD

**Issue by acoolax** [stanislavefremov/defaultselectedoptions#1]
Не работает в 3.0.3.1. Можно что-то придумать?

**Comment by stanislavefremov** [comment]
> Не работает в 3.0.3.1. Можно что-то придумать?

@acoolax  
Только что проверил на свежеустановленном Opencart 3.0.3.1 - Работает также как и на 3.0.2.0, устанавливал по своей же инструкции.
Есть ли какие-то сообщения об ошибках, и в какой момент они возникают? Еще раз попробуйте по инструкции установить пошагово, возможно, какой-то этап пропущен.

**Comment by stanislavefremov** [comment]
Нет информации подтверждающей проблему
